### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by BlueHotDog** [romul/newrelic.ex#11]
Asking because of a couple open PRs are waiting..

**Comment by sb8244** [comment]
@romul I'm willing to help as a contributor for this. I just picked up a private fork today that adds several features and fixes some warning.

**Comment by romul** [comment]
@BlueHotDog Sorry for inconvenience... Now I'm back to maintain it.
@sb8244 If you still interested, I could give you access to the repository. 2 maintainers are definitely better than one.

**Comment by sb8244** [comment]
Hey @romul I'm still interested. We use this at work and have a branch with some improvements for it (although I'd need to look if they belong here generally)

I don't know if a ton of new features should be added over time, due to the official new relic library, but changes like this or small Quality of life changes would be useful.

**Comment by romul** [comment]
@sb8244 Great, I've added you to collaborators. I guess changes that were already tested in production definitely would be useful.
